### ISSUE TITLE
my first project

### ISSUE THREAD

**Issue by shirley-wbw** [shirley-wbw/hello-world#1]
# Task
- [x] Understand GitHub and Git.
- [ ] Learn to use GitHub and Git.
- [ ] Finish the book:<GitHub入门与实践>.
